# Magicore Limine bootloader configuration
# https://github.com/limine-bootloader/limine

default_entry: 1
timeout: 0
serial: yes

/:Magicore v0.1.0
    comment: No C. No spaghetti. No 40-year debt.
    protocol: limine
    kernel_path: boot():/boot/magicore
    cmdline: console=serial loglevel=debug
